In [1]:
import gentropy.method.sumstat_imputation as sumstat_imputation

In [2]:
import numpy as np
import pandas as pd
ld=np.load("../../carmapy_light/tests/02_test_ld.npy")
ld=np.array(ld)
z=pd.read_csv("../../carmapy_light/tests/02_test_z.csv")
z=np.array(z.iloc[:,1])

In [3]:
print(ld.shape)
print(len(z))

(3390, 3390)
3390


In [4]:
import random

# Create a list of indices
indices = list(range(len(z)))

# Calculate 10% of the total indices
ten_percent = int(len(z) * 0.1)

# Randomly select 10% of the indices
unknowns = random.sample(indices, ten_percent)

# Get the remaining 90% of the indices
known = [index for index in indices if index not in unknowns]

In [5]:
print(len(unknowns))
print(len(known))

339
3051


In [6]:
sig_t = ld[known,:][:,known]
sig_i_t = ld[unknowns, :][:,known]
zt = z[known]

In [8]:
imp = sumstat_imputation.SummaryStatisticsImputation.raiss_model(zt, sig_t, sig_i_t, lamb=0.01, rtol=0.01)

In [10]:
ind=imp["imputation_r2"]>0.95
print(sum(ind))
print(np.corrcoef(z[unknowns][ind],imp["mu"][ind]))

ind=imp["imputation_r2"]>0.8
print(sum(ind))
print(np.corrcoef(z[unknowns][ind],imp["mu"][ind]))

144
[[1.         0.99411918]
 [0.99411918 1.        ]]
275
[[1.         0.98828536]
 [0.98828536 1.        ]]


In [14]:
ld = np.loadtxt("../tests/gentropy/data_samples/01_test_ld.csv", delimiter=",")
z = pd.read_csv("../tests/gentropy/data_samples/01_test_z.csv")
z = np.array(z.iloc[:, 1])

In [15]:
unknowns=[5]
known=[index for index in list(range(21)) if index not in unknowns]
sig_t = ld[known,:][:,known]
sig_i_t = ld[unknowns, :][:,known]
zt = z[known]

In [17]:
imp = sumstat_imputation.SummaryStatisticsImputation.raiss_model(zt, sig_t, sig_i_t, lamb=0.01, rtol=0.01)

In [19]:
imp["imputation_r2"][0]

0.9304069346477033

In [20]:
imp["mu"]

array([9.72148456])

In [21]:
z[unknowns]

array([-9.45046087])